# Site Configuration
site:
  title: "moseoh"
  description: "A personal blog theme for Astro."
  url: "https://polarnote.pages.dev"

# Social Links
# Configure your social media links below
# To disable a social link: set to null or remove the field entirely
# Example: twitter: null (disabled) or github: "https://github.com/username" (enabled)
social:
  github: "https://github.com/moseoh"
  linkedin: "https://www.linkedin.com/in/moseoh"
  twitter: null
  email: "azqazq195@gmail.com"

# Layout Configuration
layout:
  site_width: "1100px" # max-w-7xl
  post_width: "860px" # max-w-3xl

# Content Configuration
content:
  posts_per_page: 10

# Comments Configuration
comments:
  giscus:
    enabled: false
    script: |
      <script src="https://giscus.app/client.js"
        data-repo="moseoh/blog.moseoh.com"
        data-repo-id="R_kgDOPHXwBw"
        data-category="Q&A"
        data-category-id="DIC_kwDOPHXwB84Cs3HR"
        data-mapping="pathname"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light"
        data-lang="ko"
        crossorigin="anonymous"
        async>
      </script>
