# Site Configuration
site:
  title: "moseoh"
  description: "moseoh 개발 블로그"
  url: "https://blog.moseoh.com"

# Social Links
# Configure your social media links below
# To disable a social link: set to null or remove the field entirely
# Example: twitter: null (disabled) or github: "https://github.com/username" (enabled)
social:
  github: "https://github.com/moseoh"
  linkedin: "https://www.linkedin.com/in/moseoh"
  # twitter:
  email: "azqazq195@gmail.com"

# Layout Configuration
layout:
  site_width: "1100px" # max-w-7xl
  post_width: "860px" # max-w-3xl

# Content Configuration
content:
  posts_per_page: 10
