name: Deploy to Cloudflare

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if deploy URL is configured
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_DEPLOY_HOOKS_URL }}" ]; then
            echo "❌ CLOUDFLARE_DEPLOY_HOOKS_URL secret is not configured"
            exit 1
          fi
          echo "✅ Deploy URL is configured"

      - name: Trigger Cloudflare Deploy
        run: |
          curl -d "" "${{ secrets.CLOUDFLARE_DEPLOY_HOOKS_URL }}"

      - name: Check deployment status
        run: |
          echo "✅ Cloudflare deploy hook has been triggered"
          echo "📅 Deploy time: $(date)"
